// This file is automatically generated.
// Safe parsing for both Client and Server environments.

const defaultFirebaseConfig = {
  apiKey: "AIzaSyB1__WmAzyu6jhzmaLDBodmOC_bG9XDNl8",
  authDomain: "studio-1670844393-18cbb.firebaseapp.com",
  projectId: "studio-1670844393-18cbb",
  storageBucket: "studio-1670844393-18cbb.firebasestorage.app",
  messagingSenderId: "1049365258999",
  appId: "1:1049365258999:web:79833dc1b3c2f7b86329f2"
};

const getFirebaseConfig = () => {
  const config = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;
  if (!config) {
    return defaultFirebaseConfig;
  }
  try {
    return JSON.parse(config);
  } catch (e) {
    console.error("Failed to parse Firebase Config", e);
    return defaultFirebaseConfig;
  }
};

export const firebaseConfig = getFirebaseConfig();

if (process.env.NEXT_PUBLIC_FIREBASE_EMULATOR_HOST) {
  console.log("Using Firebase Emulators");
}
