// This file is automatically generated. Do not modify it.
// See the side effect in 'src/firebase/index.ts'

if (!process.env.NEXT_PUBLIC_FIREBASE_CONFIG) {
  throw new Error(
    'Missing NEXT_PUBLIC_FIREBASE_CONFIG environment variable'
  );
}

export const firebaseConfig = JSON.parse(
  process.env.NEXT_PUBLIC_FIREBASE_CONFIG
);

if (process.env.NEXT_PUBLIC_FIREBASE_EMULATOR_HOST) {
  console.log("Using Firebase Emulators");
}
