// This file is automatically generated.
// Safe parsing for both Client and Server environments.

const getFirebaseConfig = () => {
  const config = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;
  if (!config) {
    return {
      apiKey: "placeholder",
      authDomain: "placeholder",
      projectId: "placeholder",
      storageBucket: "placeholder",
      messagingSenderId: "placeholder",
      appId: "placeholder"
    };
  }
  try {
    return JSON.parse(config);
  } catch (e) {
    console.error("Failed to parse Firebase Config", e);
    return {};
  }
};

export const firebaseConfig = getFirebaseConfig();

if (process.env.NEXT_PUBLIC_FIREBASE_EMULATOR_HOST) {
  console.log("Using Firebase Emulators");
}
